name: rbpcp-handler
version: '0.1.0.0'
category: Bitcoin Finance Network
author: Rune K. Svendsen
maintainer: runesvend@gmail.com
copyright: 2017 Rune K. Svendsen
license: BSD3
github: runeksvendsen/rbpcp-handler

flags:
  bitcoin-testnet:
    description: "Use Bitcoin's testnet3 network (for testing)"
    manual: true
    default: false
  bitcoin-disabled:
    description: "Disable Bitcoin queries completely (for testing/benchmarking)"
    manual: true
    default: false

default-extensions:
- RecordWildCards
- OverloadedStrings
- MultiParamTypeClasses
- FunctionalDependencies
- DataKinds
- FlexibleContexts
- LambdaCase
- TypeOperators
- TypeSynonymInstances
- FlexibleInstances
- ScopedTypeVariables
- DeriveGeneric

dependencies:
- base >=4.7 && <5
## Local
- bitcoin-payment-channel     >= 1.2 && < 1.3
- bitcoin-signer
- paychan-datastore
#- bitcoin-spv-wallet
- blockchain-restful-address-index-api
- promissory-note-types
- rbpcp-api
## External
- haskoin-core
- servant-client
- servant
- http-types
- string-conversions
- text
- base16-bytestring
- mtl
- exceptions
- http-client
- http-client-tls
- errors
- either
- data-default-class
- aeson
- time
- monad-time
- tagged
- http-api-data
- monad-logger
- cereal
- zeromq4-haskell
- persistent-sqlite
- Concurrent-Cache
- transformers-base
- crypto-api
- QuickCheck
- pretty-show

library:
  ghc-options:
  - -Wall
  source-dirs: src
  exposed-modules:
  - RBPCP.Handler.FundingInfo
  - RBPCP.Handler.Open
  - RBPCP.Handler.Pay
  - RBPCP.Handler.Close
  - RBPCP.Handler.Conf
  - RBPCP.Handler.Internal.Blockchain
  - RBPCP.Handler.Internal.Funding.Test
  - RBPCP.Internal.Manager
  - RBPCP.Server
  - RBPCP.App
  - MyPrelude
  dependencies:
  - servant-server
  - wai
  - warp


executables:
  rbpcp-handler-prompt:
    other-modules:
    - TstPrelude
    - TstUtil
    main: Spec.hs
    source-dirs: test
    dependencies:
    - rbpcp-handler
    - servant-server
    - async
    - hspec
    - QuickCheck

tests:
  rbpcp-handler-test:
    other-modules:
    - TstPrelude
    - TstUtil
    main: Spec.hs
    source-dirs: test
    dependencies:
    - rbpcp-handler
    - servant-server
    - async
    - hspec
    - QuickCheck
    ghc-options:
    - -W
    - -dcore-lint
    - -debug
