#resolver: lts-7.18
resolver: nightly-2016-12-05

packages:
## App
- '.'
- '/Users/rune/IdeaProjects/blockchain-restful-address-index/blockchain-restful-address-index-api'
- '/Users/rune/IdeaProjects/promissory-note-app/bitcoin-signer'
- '/Users/rune/IdeaProjects/promissory-note-app/bitcoin-spv-wallet'
- '/Users/rune/IdeaProjects/promissory-note-app/rbpcp-api'
- '/Users/rune/IdeaProjects/promissory-note-app/paychan-datastore'
- '/Users/rune/IdeaProjects/promissory-note-app/promissory-note-types'
- '/Users/rune/IdeaProjects/bitcoin-payment-channel'
## Extra deps
- location:
    git: https://github.com/haskoin/haskoin.git
    commit: e11ff9b8375ea07bf72420401898f9d607476bb2
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
#- location:
#    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
#    commit: 81b77ab346b75b3a5dfb8d49d8925e0d3f0478e1
#  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-protocol.git
    commit: da60b36560ba48642f0c80f2944921d2ce7ef37d
  extra-dep: true
#- location: ## APISpec.Blockchain
#    git: https://github.com/runeksvendsen/blockchain-restful-address-index.git
#    commit: 1aca098c0a26fe4c39d9901199696c648b2987c0
#  extra-dep: true
#- location: ## Bitcoin.SPV.Wallet
#    git: https://github.com/runeksvendsen/bitcoin-spv-wallet.git
#    commit: b5f7fc333c9ea3e532e09965b859a8942928083e
#  extra-dep: true
- location:
    git: https://github.com/runeksvendsen/haskell-bitcoin-api.git
    commit: 5c3d774300bbc283406b6c9719f8d223e2e4f267
  extra-dep: true
- location:
    git: https://github.com/brendanhay/gogol.git
    commit: 281fd577468a01238e33c5e6acfe78945129322d
  extra-dep: true
  subdirs:
    - gogol
    - core
    - gogol-datastore
- location:
    git: https://github.com/tsuraan/bytestring-arbitrary.git
    commit: ce6234d7204d8f1faa3a7c05f4802ead210245ce
  extra-dep: true

extra-deps:
- wreq-0.5.0.0
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- cryptohash-sha256-0.11.100.1
- proto-lens-0.1.0.5
- Concurrent-Cache-0.2.2.3
- concurrent-extra-0.7.0.10
- daemons-0.2.1
- esqueleto-2.5.1
- rate-limit-1.1.1
- time-units-1.0.0

flags: {}
extra-package-dbs: []
